# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Codexa < Formula
  desc "A powerful, local-first CLI tool that ingests your codebase and allows you to ask questions about it using RAG"
  homepage "https://github.com/sahitya-chandra/codexa"
  url "https://registry.npmjs.org/codexa/-/codexa-0.1.0.tgz"
  sha256 "" # Update this with the actual SHA256 after first release: shasum -a 256 <tarball>
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match "0.1.0", shell_output("#{bin}/codexa --version")
  end
end

